## Customize pyC$^2$Ray simulation class

In this tutorial we will show you how to create your own simulation class for your own custom EoR simulation.

In [1]:
import pyc2ray as pc2r
import numpy as np, yaml
import matplotlib.pyplot as plt
import astropy.units as u
import astropy.constants as cst

2025-03-17 14:11:08.800256: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-03-17 14:11:08.826131: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2025-03-17 14:11:08.826151: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2025-03-17 14:11:08.826837: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-03-17 14:11:08.831300: I tensorflow/core/platform/cpu_feature_guar

A fundamental tool of the pyC$^2$Ray simulation is the `C2Ray` python class. This object groups the basic required functions to setup a simulation (e.g.: cosmology, time-evolution, I/O, raytracing and chemistry, etc.) and access and menages the parameters in the parameter file.

We suggest that you have a look at the tutorial on [$\S$ params_example.ipynb](params_example.ipynb) for an overview on the parameters file.

pyC$^2$Ray provides a basic class that is inheridted by the existing and more extensive class

In [2]:
sim = pc2r.C2Ray(paramfile='parameters.yml')

                 _________   ____            
    ____  __  __/ ____/__ \ / __ \____ ___  __
   / __ \/ / / / /    __/ // /_/ / __ `/ / / /
  / /_/ / /_/ / /___ / __// _, _/ /_/ / /_/ / 
 / .___/\__, /\____//____/_/ |_|\__,_/\__, /  
/_/    /____/                        /____/   

Number of GPUS 1
GPU Device ID 0: "NVIDIA RTX A1000 6GB Laptop GPU" with compute capability 8.6
Successfully allocated 536.871 Mb of device memory for grid of size N = 256, with source batch size 1
Welcome! Mesh size is N = 256.
Simulation Box size (comoving Mpc): 1.280e+02
Cosmology is on, scaling comoving quantities to the initial redshift, which is z0 = 12.000...
Cosmological parameters used:
h   = 0.6766, Tcmb0 = 2.725e+00
Om0 = 0.3097, Ob0   = 0.0490
Using power-law opacity with 10,000 table points between tau=10^(-20) and tau=10^(4)
Using Black-Body sources with effective temperature T = 5.0e+04 K and Radius  1.437e-11 rsun
Spectrum Frequency Range: 3.288e+15 to 1.316e+17 Hz
This is Energy:           1.

In [3]:
dt = sim.set_timestep(z1=11.5, z2=11.0, num_timesteps=1) * u.s
dt.to('Myr')

<Quantity 24.67858278 Myr>

In [12]:
sim.write_output??

## Existing Sub-class

This tutorial is all about changing the methods of the basic class of the pyC$^2$Ray run.

We provide a series of standard class can be `C2Ray_Test` class. This subclass of the basic class `C2Ray` is a version used for test simulations and which don't read N-body input and use simple generated source files.

All the sub-class require a parameter file `parameters.yml` as input.

- `c2ray_base.py`: implemented the basic function 
- `c2ray_cubep3m.py`: specific for CUBEP3M N-body
- `c2ray_ramses.py`: specific for Ramses hyro N-body simulation
- ... more to come

In [2]:
sim = pc2r.C2Ray_Test(paramfile='parameters.yml')

GPU Device 0: "NVIDIA RTX A1000 6GB Laptop GPU" with compute capability 8.6
Succesfully allocated 67.1089 Mb of device memory for grid of size N = 128, with source batch size 1
                 _________   ____            
    ____  __  __/ ____/__ \ / __ \____ ___  __
   / __ \/ / / / /    __/ // /_/ / __ `/ / / /
  / /_/ / /_/ / /___ / __// _, _/ /_/ / /_/ / 
 / .___/\__, /\____//____/_/ |_|\__,_/\__, /  
/_/    /____/                        /____/   

Welcome! Mesh size is N = 128.
Simulation Box size (comoving Mpc): 1.400e-02
Cosmology is off.
Using power-law opacity with 10000 table points between tau=10^(-20) and tau=10^(4)
Using Black-Body sources with effective temperature T = 5.0e+04 K and Radius  1.437e-11 rsun
Spectrum Frequency Range: 3.289e+15 to 1.316e+17 Hz
This is Energy:           1.360e+01 to 5.442e+02 eV
Integrating photoionization rates tables...
INFO: No heating rates
Successfully copied radiation tables to GPU memory.

---- Calculated Clumping Factor (constant mod

## Write a Sub-class for your simulation

In [7]:
class C2Ray_tutorial(pc2r.c2ray_base.C2Ray):
    def __init__(self, paramfile):
        """Basis class for a C2Ray Simulation

        Parameters
        ----------
        paramfile : str
            Name of a YAML file containing parameters for the C2Ray simulation
        """
        super().__init__(paramfile)
        self.printlog('Running: "C2Ray tutorial for %d Mpc/h volume"' %self.boxsize)

    # ===========================================
    # HEREAFTER: USER DEFINED METHODS
    # ===========================================
    
    def read_sources(self, z, nsrc, dt):
        np.random.seed(918)
        
        # Read random sources (e.g.: *.npy, *.h5, etc.)
        pos_halo = np.random.uniform(low=0, high=sim.boxsize, size=(nsrc, 3))
        mhalo = np.random.uniform(1e8, 1e14, nsrc)*u.Msun

        # Define stellar-to-halo relation
        fstar = 0.1
        
        # Define escaping fraction
        fesc = 0.1
        
        # sum togheter the star mass for sources within the same voxel
        pos_star, mstar = pc2r.other_utils.bin_sources(srcpos_mpc=pos_halo, mstar_msun=mhalo*fstar*fesc, boxsize=sim.boxsize, meshsize=sim.N)
        
        """
        pos_star = np.array([sim.N//2, sim.N//2, sim.N//2])
        pos_star = pos_star[None,...]
        mstar = np.array([1e14])
        """        
        
        # this reference flux is necessary only for a numercial reason
        S_star_ref = 1e48
        
        # The normalize flux in CGS units
        dotN = (mstar*u.Msun/(cst.m_p*dt)).cgs.value
        
        # calculate some quantity thtat you want to print (e.g. total number of ionizing photons)
        self.tot_phots = np.sum(dotN * dt)

        return pos_star, dotN/S_star_ref
    
    def read_density(self, z):
        # Read the density field
        self.ndens = 1e-6 * np.ones((sim.N, sim.N, sim.N))
        return self.ndens

In [9]:
paramfile = './parameters.yml'

# init the C2Ray class for the tutorial
sim = C2Ray_tutorial(paramfile)

Number of GPUS 1
                 _________   ____            
    ____  __  __/ ____/__ \ / __ \____ ___  __
   / __ \/ / / / /    __/ // /_/ / __ `/ / / /
  / /_/ / /_/ / /___ / __// _, _/ /_/ / /_/ / 
 / .___/\__, /\____//____/_/ |_|\__,_/\__, /  
/_/    /____/                        /____/   

GPU Device ID 0: "NVIDIA RTX A1000 6GB Laptop GPU" with compute capability 8.6
Successfully allocated 536.871 Mb of device memory for grid of size N = 256, with source batch size 1
Welcome! Mesh size is N = 256.
Simulation Box size (comoving Mpc): 1.280e+02
Cosmology is on, scaling comoving quantities to the initial redshift, which is z0 = 12.000...
Cosmological parameters used:
h   = 0.6766, Tcmb0 = 2.725e+00
Om0 = 0.3097, Ob0   = 0.0490
Using power-law opacity with 10,000 table points between tau=10^(-20) and tau=10^(4)
Using Black-Body sources with effective temperature T = 5.0e+04 K and Radius  1.437e-11 rsun
Spectrum Frequency Range: 3.288e+15 to 1.316e+17 Hz
This is Energy:           1.

In [12]:
# Read homogeneous density field
ndens = sim.read_density(z=7.0)

In [17]:
# Read source files
srcpos, normflux = sim.read_sources(nsrc=10, z=7.0, dt=10.*u.Myr)
print(srcpos)

[[ 15 187  45]
 [ 15 218   1]
 [ 33  93  31]
 [ 50  28 170]
 [ 96 156 213]
 [185 199 122]
 [192 232 217]
 [224 121 197]
 [243 150 229]
 [255  90 252]]


In [18]:
sim.cosmology.H0

<Quantity 67.66 km / (Mpc s)>